version: '3.8'

services:
  # 1. Database MySQL
  db:
    image: mysql:8.0
    container_name: koopcare_mysql
    restart: always
    environment:
      MYSQL_DATABASE: koopcare_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: koopcare_user
      MYSQL_PASSWORD: koopcarepassword
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/migrations:/migrations
      - ./backend/seed.sql:/seed.sql
      - ./backend/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5


  # 2. Backend Node.js API
  backend:
    build: ./backend
    container_name: koopcare_backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USER=koopcare_user
      - DB_PASSWORD=koopcarepassword
      - DB_NAME=koopcare_db
      - JWT_SECRET=supersecretkoopcarekey
      - NODE_ENV=development
      # - ML_API_BASE_URL=http://host.docker.internal:8000
      - ML_API_BASE_URL=https://koopcare-mlops-credit-scoring-api-production.up.railway.app
      - ML_API_TIMEOUT_MS=5000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules   # jangan mount node_modules dari host
    command: sh -c "npm install && npm run dev"

  # 3. Frontend React Vite
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: koopcare_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5001/api/v1
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  db_data:
