export const TRANSACTION_TYPES = {
  DEPOSIT_WAJIB: 'SETORAN_WAJIB',
  WITHDRAWAL: 'TARIK_TUNAI',
  INSTALLMENT_PAYMENT: 'BAYAR_ANGSURAN',
  TOP_UP: 'TOP_UP_SALDO',
  WITHDRAW_SALDO: 'PENARIKAN_SALDO',
  TRANSFER: 'TRANSFER',
};

export const LOAN_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  ACTIVE: 'ACTIVE',
  PAID_OFF: 'PAID_OFF',
  DEFAULTED: 'DEFAULTED',
};

export const KYC_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

export const MEMBER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

export const ROLE = {
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
};